info:
    serviceLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}"
    podLinks:
        metrics: "{metricsHostname}/dashboard/db/openshift-project-spring-actuator-view-instance?var-ds=openshift-{cluster}-ose&var-namespace={namespace}&var-app={name}&var-instance={podName}"

openshift:
    cluster: utv
    url: https://${openshift.cluster}-master.paas.skead.no:8443


spring:
  profiles:
    active: local

logging:
  level:
    no.skatteetaten: INFO
    org:
      jboss: WARN
      hibernate: WARN
      springframework: WARN
      apache:
        catalina: WARN
        velocity: WARN
---
spring:
    profiles: local

---
spring:
  profiles: openshift

